#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Feb  2 12:32:54 2018

@author: edwardtaylor
"""


import numpy as np

sfile = '/Users/edwardtaylor/Desktop/data.txt'
tp = np.genfromtxt(sfile,dtype=np.str, delimiter=20)
print(tp)
i = 0
def separate_bits(array):
    for i in range(len(array)):
        return np.split(array,len(array))
def hex_to_dex(strng_of_hex):
    return int(strng_of_hex, 16)
print(separate_bits(tp))
print(len(tp)/435)
ar = separate_bits(tp)

